name: cyfl_oem_app
description: oem app
version: 0.0.4
homepage: https://www.solarpilot.com/

environment:
  sdk: '>=2.19.6 <3.0.0'

executables:
  cyfl_oem:

dependencies:
  args: ^2.3.0
  logger: ^2.0.2+1
  path: ^1.8.0
